### ISSUE TITLE
Missing `thedrum/php:7.2-apache`

### ISSUE THREAD

**Issue by chrisshennan** [thedrum-developers/docker-php#12]
The latest modification which add a new dev docker image `thedrum/php:7.2-apache-dev` (https://github.com/thedrum-developers/docker-php/commit/2b63c8113a27a23419c071c5fe8af60357ae43a5) uses the base image `thedrum/php:7.2-apache` but there isn't a base image for `thedrum/php:7.2-apache` in the repo.

**Comment by pullthefuse** [comment]
Fixed!!
